### ISSUE TITLE
因为虚拟asio驱动问题导致播放声音失败，怎么指定物理音频设备？

### ISSUE THREAD

**Issue by ms903x1** [kslz/SoundLabel#11]
![asio](https://user-images.githubusercontent.com/108673569/198866670-089bf3d9-c2bc-425f-992f-ef3ef5196fe1.png)

**Comment by ms903x1** [comment]
或者禁止程序调用asio驱动也行。

**Comment by kslz** [comment]
我没用过asio驱动，知识的盲区
不过可以尝试一下指定播放设备，会有效吗？

**Comment by kslz** [comment]
我提新代码了 你可以试一下

**Comment by ms903x1** [comment]
> 我提新代码了 你可以试一下

感谢，我这就去试试。

![QQ截图20221031120656](https://user-images.githubusercontent.com/108673569/198929167-2731889a-ce7f-4f90-a0aa-d671857e0ad3.png)
![QQ截图20221031120333](https://user-images.githubusercontent.com/108673569/198929189-0083d8ef-b287-4d8b-ac8a-0b2f4d602436.png)




指定了播放设备依然不行，不过我昨天找到暂时的解决方法了，就是在虚拟机上运行，可以正常播放声音，实体机也能听到。

**Comment by kslz** [comment]
寄
