### ISSUE TITLE
你好，请问是只支持中文吗

### ISSUE THREAD

**Issue by ulen2000** [kslz/SoundLabel#16]
你好，请问是只支持中文吗

**Comment by kslz** [comment]
> 你好，请问是只支持中文吗

目前是，有什么相关的需求吗

**Comment by ulen2000** [comment]
谢谢。 目前是想做英文方面的语音数据集，但是苦于找不到类似的这么好的数据集制作工具，您有推荐的么？

**Comment by kslz** [comment]
> 谢谢。 目前是想做英文方面的语音数据集，但是苦于找不到类似的这么好的数据集制作工具，您有推荐的么？

我在更新这个项目，最近可能加一下对英文的支持sound_dataset_tools2

你现在是有字幕和音频，只欠切割？
目前这个项目会跳过英文和数字的数据，我需要改改才能导出英文数据

**Comment by ulen2000** [comment]
是的，只欠切割，期待项目的升级

**Comment by kslz** [comment]
> 是的，只欠切割，期待项目的升级

好了，你可以去隔壁项目克隆代码了，如果你需要exe文件那还得再等下

**Comment by kslz** [comment]
exe也更新好了 我就先关啦
https://github.com/kslz/sound_dataset_tools2
